/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/heroes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available hero templates
         * @description Returns all active, unlocked hero templates available for minting.
         *     Each entry includes supply info so agents can check availability.
         */
        get: operations["listHeroes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all local characters
         * @description Returns all characters for the local user session.
         */
        get: operations["listCharacters"];
        put?: never;
        /**
         * Create a new character
         * @description Creates a character with chosen race and class. Optionally link to
         *     an on-chain hero NFT via heroTokenId and ownerAddress.
         */
        post: operations["createCharacter"];
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update character owner address
         * @description Sets or updates the ownerAddress on a character. Prevents double-claiming.
         */
        patch: operations["updateCharacterOwner"];
        trace?: never;
    };
    "/api/characters/owned": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List characters owned by wallet
         * @description Returns characters linked to a specific wallet address, ordered by last played.
         */
        get: operations["listOwnedCharacters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Claim a hero NFT and create character
         * @description Claims a hero template, verifies on-chain NFT ownership, and creates the character.
         *     The wallet must actually own the token on-chain.
         */
        post: operations["claimHero"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/burn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete a character
         * @description Permanently deletes a character and all associated party companions.
         */
        post: operations["burnCharacter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/equip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Equip or unequip an item
         * @description Equips an item from inventory to a slot, or unequips a slot back to inventory.
         *     Stats are recalculated after equipment changes.
         */
        post: operations["equipItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/sync-owner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Sync owner after on-chain NFT transfer
         * @description Verifies on-chain ownership of the hero NFT and updates the character's
         *     ownerAddress to match the current on-chain owner.
         */
        patch: operations["syncOwner"];
        trace?: never;
    };
    "/api/party": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get hero and companion party
         * @description Returns the hero character and their 5-slot companion party.
         *     Empty slots are null.
         */
        get: operations["getParty"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/party/forge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create full 5-companion party at once
         * @description Replaces the entire companion party with 5 new companions.
         *     Existing companions are moved to the bench. Used after minting
         *     a party NFT on-chain.
         */
        post: operations["forgeParty"];
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Link minted companions to soulbound token IDs
         * @description After minting companion NFTs on-chain, link token IDs to DB records.
         */
        patch: operations["linkCompanionTokens"];
        trace?: never;
    };
    "/api/party/companions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List companions for a wallet
         * @description Returns companions owned by a wallet. Can filter by hero or unassigned (bench).
         */
        get: operations["listCompanions"];
        put?: never;
        /**
         * Create a single companion in a party slot
         * @description Creates a companion and assigns it to a specific slot (1-5) on a hero's party.
         */
        post: operations["createCompanion"];
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Reassign companion to different hero/slot or bench
         * @description Moves a companion to a new slot on a hero, or benches it by setting
         *     heroCharacterId to null. If the target slot is occupied, the occupant
         *     is swapped to the bench.
         */
        patch: operations["reassignCompanion"];
        trace?: never;
    };
    "/api/party/companions/bench": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create companion directly on bench
         * @description Creates an unassigned companion that can later be slotted into a party.
         */
        post: operations["createBenchCompanion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/party/companions/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate companion lore and images via AI
         * @description Uses Gemini to generate a companion's lore (name, backstory, abilities, appearance)
         *     and portrait/avatar images. Use the output to create a companion.
         */
        post: operations["generateCompanion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/game/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get character state, combat, and zone info
         * @description Returns the full game state for a character: their stats, any active
         *     combat session, and current zone details.
         */
        get: operations["getGameState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/game/travel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Move character to an adjacent zone
         * @description Moves the character to a connected zone. The target zone must be
         *     reachable from the current zone via its connections list.
         */
        post: operations["travel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/game/respawn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Respawn character at bind point
         * @description Restores HP/mana to full and optionally returns character to their bind zone.
         *     Use after death to get back into the game.
         */
        post: operations["respawn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/game/action": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send action to AI game master (SSE stream)
         * @description Sends a free-text message to the AI game master and receives a
         *     streamed narrative response via Server-Sent Events. The game master
         *     handles exploration, NPC dialogue, lore, and story progression.
         */
        post: operations["gameAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/game/token-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check wallet token requirements
         * @description Checks if a wallet holds the required tokens to access a hero template.
         *     Verifies on-chain ERC20 balances against configured requirements.
         */
        post: operations["tokenCheck"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/combat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get active combat session
         * @description Returns the current combat state for a character, or null if not in combat.
         */
        get: operations["getCombat"];
        put?: never;
        /**
         * Initiate, tick, or flee combat
         * @description Manages classic auto-combat. Use action "initiate" to start fighting
         *     zone mobs, "tick" to advance rounds, and "flee" to escape.
         */
        post: operations["combatAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/battle/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a card-based battle session
         * @description Initiates a turn-based card battle against waves of mobs.
         *     Includes the hero and up to 5 companions as player units.
         */
        post: operations["startBattle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/battle/action": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute a turn in card battle
         * @description Submits an action for the current unit's turn. The server processes
         *     the action, advances the turn order, and returns updated state.
         */
        post: operations["battleAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pvp/lobby": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List waiting PvP matches
         * @description Returns all matches with status "waiting" that can be joined.
         */
        get: operations["getPvPLobby"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pvp/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a PvP match
         * @description Creates a new PvP match and waits for an opponent to join.
         *     Requires a full party (hero + 5 companions).
         */
        post: operations["createPvPMatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pvp/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Join a waiting PvP match
         * @description Joins an existing PvP match as player 2. Initializes the full battle
         *     state and sets status to "active". Requires a full party.
         */
        post: operations["joinPvPMatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pvp/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get PvP match state
         * @description Returns the current state of a PvP match. When active, returns a
         *     fog-of-war filtered view specific to the requesting player.
         */
        get: operations["getPvPState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pvp/action": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute a turn in PvP battle
         * @description Submits a battle action for the current turn. Must be your turn
         *     (check currentPlayerSide). Returns your player-specific view of
         *     the updated state.
         */
        post: operations["pvpAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List active and available quests
         * @description Returns the character's active quests and quests available in the
         *     current or specified zone.
         */
        get: operations["listQuests"];
        put?: never;
        /**
         * Accept, progress, or complete a quest
         * @description Manages quest lifecycle. Accept to start tracking, progress to update
         *     objective counts, complete to finish and claim rewards.
         */
        post: operations["questAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List or lookup items
         * @description Returns items from the game catalog. Filter by ID for single lookup,
         *     or by class/slot/type for browsing.
         */
        get: operations["listItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/merchant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List merchants or get merchant inventory
         * @description Get merchants in a zone or a specific merchant's inventory.
         *     At least one of zoneId or merchantId must be provided.
         */
        get: operations["getMerchants"];
        put?: never;
        /**
         * Buy or sell items at a merchant
         * @description Executes a buy or sell transaction. Currency is automatically converted
         *     between platinum/gold/silver/copper denominations.
         */
        post: operations["merchantTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get ranked character leaderboard
         * @description Returns characters ranked by level and XP. Only characters with
         *     on-chain ownership (ownerAddress set) are included.
         */
        get: operations["getLeaderboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/faucet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request testnet ETH (Hardhat only)
         * @description Sends 1 ETH from the Hardhat default account to the specified address.
         *     Only works when CHAIN_ID is 31337 (local Hardhat network).
         */
        post: operations["requestFaucet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        RaceId: "human" | "barbarian" | "erudite" | "wood_elf" | "high_elf" | "dark_elf" | "half_elf" | "dwarf" | "troll" | "ogre" | "halfling" | "gnome" | "iksar";
        /** @enum {string} */
        ClassId: "warrior" | "cleric" | "paladin" | "ranger" | "shadowknight" | "druid" | "monk" | "bard" | "rogue" | "shaman" | "necromancer" | "wizard" | "magician" | "enchanter";
        /** @enum {string} */
        ClassArchetype: "melee" | "hybrid" | "priest" | "caster";
        /** @enum {string} */
        ActionType: "attack" | "spell" | "defend";
        /** @enum {string} */
        BattleStatus: "active" | "won" | "lost";
        /** @enum {string} */
        PvPStatus: "waiting" | "active" | "completed";
        /** @enum {string|null} */
        PvPResult: "player1" | "player2" | "draw" | null;
        /**
         * @default medium
         * @enum {string}
         */
        BattleDifficulty: "easy" | "medium" | "hard";
        /** @enum {string} */
        QuestStatus: "available" | "active" | "completed" | "failed";
        /** @enum {string} */
        ObjectiveType: "kill" | "collect" | "deliver" | "explore" | "talk" | "escort";
        /** @enum {string} */
        ItemType: "weapon" | "armor" | "jewelry" | "spell" | "food" | "drink" | "container" | "key" | "misc";
        /** @enum {string} */
        WeaponType: "1h_slashing" | "2h_slashing" | "1h_blunt" | "2h_blunt" | "piercing" | "archery" | "throwing" | "hand_to_hand";
        /** @enum {string} */
        ArmorSlot: "head" | "face" | "ear" | "neck" | "chest" | "arms" | "wrist" | "hands" | "ring" | "back" | "waist" | "legs" | "feet" | "primary" | "secondary" | "ammo" | "range";
        /** @enum {string} */
        DamageType: "melee" | "magic" | "fire" | "cold" | "poison" | "disease" | "piercing" | "slashing" | "blunt";
        BaseStats: {
            str: number;
            dex: number;
            sta: number;
            cha: number;
            wis: number;
            int: number;
            agi: number;
        };
        CharacterStats: components["schemas"]["BaseStats"] & {
            maxHp?: number;
            maxMana?: number;
            ac?: number;
            atk?: number;
            hpRegen?: number;
            manaRegen?: number;
            svFire?: number;
            svCold?: number;
            svPoison?: number;
            svMagic?: number;
            svDisease?: number;
            weight?: number;
            maxWeight?: number;
        };
        /** @description Equipment slots — each value is an item ID or null */
        Equipment: {
            primary?: string;
            secondary?: string;
            head?: string;
            chest?: string;
            legs?: string;
            feet?: string;
            hands?: string;
            arms?: string;
            back?: string;
            neck?: string;
            waist?: string;
            ring1?: string;
            ring2?: string;
            ear1?: string;
            ear2?: string;
            wrist1?: string;
            wrist2?: string;
            face?: string;
            ammo?: string;
        };
        Currency: {
            platinum: number;
            gold: number;
            silver: number;
            copper: number;
        };
        /** @description Stat bonuses from an item (all optional) */
        ItemStats: {
            str?: number;
            dex?: number;
            sta?: number;
            cha?: number;
            wis?: number;
            int?: number;
            agi?: number;
            hp?: number;
            mana?: number;
            ac?: number;
            svFire?: number;
            svCold?: number;
            svPoison?: number;
            svMagic?: number;
            svDisease?: number;
            atk?: number;
            hpRegen?: number;
            manaRegen?: number;
        };
        ErrorResponse: {
            error: string;
        };
        Character: {
            id: string;
            userId: string;
            name: string;
            raceId: components["schemas"]["RaceId"];
            classId: components["schemas"]["ClassId"];
            level: number;
            xp: number;
            xpToNextLevel?: number;
            currentHp: number;
            maxHp: number;
            currentMana?: number;
            maxMana?: number;
            stats?: components["schemas"]["CharacterStats"];
            baseStats?: components["schemas"]["BaseStats"];
            equipment?: components["schemas"]["Equipment"];
            /** @description Array of item IDs */
            inventory?: string[];
            currency?: components["schemas"]["Currency"];
            currentZoneId?: string;
            bindZoneId?: string;
            /** Format: date-time */
            lastPlayedAt?: string;
            /** Format: date-time */
            createdAt?: string;
            ownerAddress?: string | null;
            heroTokenId?: number | null;
            avatarIpfs?: string | null;
            portraitIpfs?: string | null;
            heroLoreJson?: string | null;
        };
        /** @description Lighter character view for wallet-owned listings */
        OwnedCharacter: {
            id?: string;
            name?: string;
            raceId?: components["schemas"]["RaceId"];
            classId?: components["schemas"]["ClassId"];
            level?: number;
            xp?: number;
            currentZoneId?: string;
            heroTokenId?: number | null;
            ownerAddress?: string;
            portraitIpfs?: string | null;
            avatarIpfs?: string | null;
            /** Format: date-time */
            lastPlayedAt?: string;
            templateId?: string | null;
            heroLoreJson?: string | null;
        };
        /** @description Hero template available for minting */
        PublicHero: {
            id?: string;
            name?: string;
            raceId?: components["schemas"]["RaceId"];
            classId?: components["schemas"]["ClassId"];
            level?: number;
            portraitIpfs?: string | null;
            avatarIpfs?: string | null;
            lore?: ({
                epithet?: string;
                backstory?: string;
            } & {
                [key: string]: unknown;
            }) | null;
            maxSupply?: number;
            mintedCount?: number;
            /** @description Computed from maxSupply (common, uncommon, rare, epic, legendary) */
            rarity?: string;
            available?: boolean;
            onChainTemplateId?: number;
            /** Format: date-time */
            createdAt?: string;
        };
        Item: {
            id: string;
            name: string;
            type: components["schemas"]["ItemType"];
            weight: number;
            /** @description Value in copper */
            value: number;
            /** @description If true, only 1 allowed in inventory */
            lore?: boolean;
            noTrade?: boolean;
            noDrop?: boolean;
            classes?: components["schemas"]["ClassId"][];
            races?: components["schemas"]["RaceId"][];
            stats?: components["schemas"]["ItemStats"];
            description?: string;
            weaponType?: components["schemas"]["WeaponType"];
            /** @description Weapon damage */
            damage?: number;
            /** @description Weapon delay in tenths of seconds */
            delay?: number;
            damageType?: components["schemas"]["DamageType"];
            slot?: components["schemas"]["ArmorSlot"];
            /** @description Armor AC bonus */
            acBonus?: number;
        };
        ZoneConnection: {
            toZoneId?: string;
            toZoneName?: string;
            direction?: string;
            description?: string;
            requiresKey?: string;
        };
        Zone: {
            id?: string;
            name?: string;
            shortName?: string;
            description?: string;
            ambiance?: string;
            level?: {
                min?: number;
                max?: number;
            };
            connections?: components["schemas"]["ZoneConnection"][];
            safeZone?: boolean;
            bindable?: boolean;
            /** @enum {string} */
            continent?: "antonica" | "faydwer" | "odus" | "kunark" | "velious" | "luclin";
        };
        Quest: {
            id?: string;
            title?: string;
            description?: string;
            /** @description NPC ID or "world" */
            giver?: string;
            giverZoneId?: string;
            minLevel?: number;
            maxLevel?: number;
            objectives?: components["schemas"]["QuestObjective"][];
            rewards?: components["schemas"]["QuestReward"];
            lore?: string;
            prerequisiteQuestIds?: string[];
        };
        QuestObjective: {
            id?: string;
            type?: components["schemas"]["ObjectiveType"];
            description?: string;
            targetId?: string;
            targetCount?: number;
            currentCount?: number;
            completed?: boolean;
        };
        QuestReward: {
            xp?: number;
            gold?: number;
            items?: string[];
        };
        CharacterQuest: {
            questId?: string;
            status?: components["schemas"]["QuestStatus"];
            objectives?: components["schemas"]["QuestObjective"][];
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            completedAt?: string;
        };
        Ability: {
            id?: string;
            name?: string;
            /** @enum {string} */
            type?: "attack" | "spell" | "heal" | "buff" | "debuff";
            manaCost?: number;
            damage?: number;
            healing?: number;
            description?: string;
            /** @enum {string} */
            targetType?: "single_enemy" | "all_enemies" | "single_ally" | "all_allies" | "self";
        };
        /** @description A player unit in card battle (hero or companion) */
        CardUnit: {
            id?: string;
            name?: string;
            classId?: components["schemas"]["ClassId"];
            raceId?: components["schemas"]["RaceId"];
            level?: number;
            xp?: number;
            currentHp?: number;
            maxHp?: number;
            currentMana?: number;
            maxMana?: number;
            atk?: number;
            ac?: number;
            str?: number;
            dex?: number;
            agi?: number;
            abilities?: components["schemas"]["Ability"][];
            isHero?: boolean;
            portraitUrl?: string | null;
        };
        /** @description An enemy unit in card battle */
        BattleMob: {
            id?: string;
            name?: string;
            level?: number;
            currentHp?: number;
            maxHp?: number;
            atk?: number;
            ac?: number;
            abilities?: components["schemas"]["Ability"][];
            xpValue?: number;
            portraitEmoji?: string;
            portraitUrl?: string | null;
        };
        BattleAction: {
            actorId: string;
            type: components["schemas"]["ActionType"];
            targetId: string;
            abilityId?: string;
        };
        BattleLogEntry: {
            round?: number;
            actorId?: string;
            actorName?: string;
            targetId?: string;
            targetName?: string;
            actionType?: components["schemas"]["ActionType"];
            damage?: number;
            healing?: number;
            isCrit?: boolean;
            isMiss?: boolean;
            message?: string;
        };
        BattleWave: {
            waveNumber?: number;
            mobs?: components["schemas"]["BattleMob"][];
            isBoss?: boolean;
        };
        UnitReward: {
            id?: string;
            name?: string;
            isHero?: boolean;
            classId?: string;
            survived?: boolean;
            xpGained?: number;
            oldLevel?: number;
            newLevel?: number;
            leveledUp?: boolean;
        };
        BattleRewards: {
            totalXp?: number;
            xpPerUnit?: number;
            unitRewards?: components["schemas"]["UnitReward"][];
        };
        BattleState: {
            sessionId?: string;
            characterId?: string;
            wave?: number;
            waves?: components["schemas"]["BattleWave"][];
            playerUnits?: components["schemas"]["CardUnit"][];
            enemyUnits?: components["schemas"]["BattleMob"][];
            turnOrder?: string[];
            /** @description ID of the unit whose turn it is */
            currentTurn?: string;
            log?: components["schemas"]["BattleLogEntry"][];
            status?: components["schemas"]["BattleStatus"];
            round?: number;
            xpAwarded?: number;
            defendingIds?: string[];
            /** @description enemyId → playerUnitId forcing attack on taunter */
            tauntTargets?: {
                [key: string]: string;
            };
            slowedIds?: string[];
            mesmerizedIds?: string[];
            rewards?: components["schemas"]["BattleRewards"];
        };
        PvPBattleState: {
            matchId?: string;
            player1Units?: components["schemas"]["CardUnit"][];
            player2Units?: components["schemas"]["CardUnit"][];
            turnOrder?: string[];
            currentTurn?: string;
            /** @enum {string} */
            currentPlayerSide?: "player1" | "player2";
            log?: components["schemas"]["BattleLogEntry"][];
            round?: number;
            status?: components["schemas"]["PvPStatus"];
            winner?: components["schemas"]["PvPResult"];
            defendingIds?: string[];
            tauntTargets?: {
                [key: string]: string;
            };
            slowedIds?: string[];
            mesmerizedIds?: string[];
            player1CharacterId?: string;
            player2CharacterId?: string;
            /** Format: date-time */
            lastActionAt?: string;
        };
        PvPLobbyEntry: {
            matchId?: string;
            player1Name?: string;
            player1Class?: string;
            player1Level?: number;
            partySize?: number;
            /** Format: date-time */
            createdAt?: string;
        };
        CombatParticipant: {
            id?: string;
            name?: string;
            isPlayer?: boolean;
            currentHp?: number;
            maxHp?: number;
            currentMana?: number;
            maxMana?: number;
            level?: number;
            ac?: number;
            atk?: number;
            str?: number;
            dex?: number;
            agi?: number;
            mobTemplateId?: string;
            xpValue?: number;
            lootTable?: string[];
        };
        DamageEvent: {
            attackerId?: string;
            defenderId?: string;
            damage?: number;
            damageType?: components["schemas"]["DamageType"];
            isCrit?: boolean;
            isMiss?: boolean;
            isBlock?: boolean;
            isParry?: boolean;
            isDodge?: boolean;
            spellId?: string;
            message?: string;
        };
        CombatRound: {
            roundNumber?: number;
            timestamp?: number;
            events?: components["schemas"]["DamageEvent"][];
            stateAfter?: {
                participants?: {
                    id?: string;
                    currentHp?: number;
                    currentMana?: number;
                }[];
            };
            narrative?: string;
        };
        CombatState: {
            sessionId?: string;
            characterId?: string;
            participants?: components["schemas"]["CombatParticipant"][];
            round?: number;
            isActive?: boolean;
            /** @enum {string} */
            outcome?: "victory" | "defeat" | "fled";
            startedAt?: number;
            rounds?: components["schemas"]["CombatRound"][];
            totalXpAwarded?: number;
        };
        GameStateResponse: {
            character?: components["schemas"]["Character"];
            combatState?: components["schemas"]["CombatState"] | null;
            zone?: components["schemas"]["Zone"] | null;
        };
        PartyResponse: {
            hero?: components["schemas"]["Character"];
            /** @description 5 slots (index 0-4), null if empty */
            companions?: (components["schemas"]["Companion"] | null)[];
        };
        /** @description Party companion (NPC party member) */
        Companion: {
            id?: string;
            heroCharacterId?: string | null;
            ownerAddress?: string;
            /** @description 1-5 when assigned, 0 when benched */
            slotIndex?: number;
            name?: string;
            archetype?: string;
            backstoryJson?: string;
            raceId?: string | null;
            classId?: string | null;
            level?: number;
            xp?: number;
            avatarUrl?: string | null;
            portraitUrl?: string | null;
            soulboundTokenId?: number | null;
            /** Format: date-time */
            createdAt?: string;
        };
        LeaderboardEntry: {
            rank?: number;
            id?: string;
            name?: string;
            raceId?: components["schemas"]["RaceId"];
            classId?: components["schemas"]["ClassId"];
            level?: number;
            xp?: number;
            currentZoneId?: string;
            ownerAddress?: string;
            portraitIpfs?: string | null;
            templateId?: string | null;
        };
        Merchant: {
            id?: string;
            name?: string;
            zoneId?: string;
            inventory?: {
                itemId?: string;
                quantity?: number;
                priceCopper?: number;
            }[];
            buyMultiplier?: number;
            sellMultiplier?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listHeroes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of hero templates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "id": "tmpl_shadowknight_iksar",
                     *         "name": "Kazrak the Undying",
                     *         "raceId": "iksar",
                     *         "classId": "shadowknight",
                     *         "level": 1,
                     *         "portraitIpfs": "QmXyz...",
                     *         "avatarIpfs": "QmAbc...",
                     *         "lore": {
                     *           "epithet": "The Undying",
                     *           "backstory": "Once a feared general of Cabilis..."
                     *         },
                     *         "maxSupply": 100,
                     *         "mintedCount": 12,
                     *         "rarity": "rare",
                     *         "available": true,
                     *         "onChainTemplateId": 3,
                     *         "createdAt": "2025-01-15T10:00:00Z"
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["PublicHero"][];
                };
            };
        };
    };
    listCharacters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of characters */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Character"][];
                };
            };
        };
    };
    createCharacter: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "name": "Kazrak",
                 *       "raceId": "iksar",
                 *       "classId": "shadowknight",
                 *       "ownerAddress": "0x1234567890abcdef1234567890abcdef12345678"
                 *     }
                 */
                "application/json": {
                    name: string;
                    raceId: components["schemas"]["RaceId"];
                    classId: components["schemas"]["ClassId"];
                    /** @description Optional stat overrides */
                    bonusStats?: {
                        [key: string]: number;
                    };
                    /** @description NFT token ID if claiming on-chain hero */
                    heroTokenId?: number;
                    /** @description EVM wallet address */
                    ownerAddress?: string;
                    portraitIpfs?: string | null;
                    avatarIpfs?: string | null;
                    heroLore?: {
                        [key: string]: unknown;
                    } | null;
                };
            };
        };
        responses: {
            /** @description Character created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Character"];
                };
            };
            /** @description Invalid race/class combo or name taken */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateCharacterOwner: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    characterId: string;
                    ownerAddress: string;
                };
            };
        };
        responses: {
            /** @description Updated character */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Character"];
                };
            };
            /** @description Already claimed by another wallet */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listOwnedCharacters: {
        parameters: {
            query: {
                /**
                 * @description Wallet address (lowercase)
                 * @example 0x1234567890abcdef1234567890abcdef12345678
                 */
                address: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of owned characters */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnedCharacter"][];
                };
            };
            /** @description Missing address */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    claimHero: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "templateId": "tmpl_shadowknight_iksar",
                 *       "tokenId": 42,
                 *       "ownerAddress": "0x1234567890abcdef1234567890abcdef12345678"
                 *     }
                 */
                "application/json": {
                    templateId: string;
                    /** @description NFT token ID */
                    tokenId: number | string;
                    ownerAddress: string;
                    /** @description Override template name */
                    customName?: string;
                };
            };
        };
        responses: {
            /** @description Character created from hero template */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Character"];
                };
            };
            /** @description Template locked, supply exhausted, or ownership check failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    burnCharacter: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "characterId": "chr_abc123"
                 *     }
                 */
                "application/json": {
                    characterId: string;
                };
            };
        };
        responses: {
            /** @description Character deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "ok": true,
                     *       "deleted": "chr_abc123"
                     *     }
                     */
                    "application/json": {
                        /** @example true */
                        ok?: boolean;
                        deleted?: string;
                    };
                };
            };
            /** @description Character not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    equipItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "characterId": "chr_abc123",
                 *       "action": "equip",
                 *       "itemId": "rusty_short_sword",
                 *       "slot": "primary"
                 *     }
                 */
                "application/json": {
                    characterId: string;
                    /** @enum {string} */
                    action: "equip" | "unequip";
                    /** @description Required when action is 'equip' */
                    itemId?: string;
                    slot: components["schemas"]["ArmorSlot"];
                };
            };
        };
        responses: {
            /** @description Equipment updated with recalculated stats */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        equipment?: components["schemas"]["Equipment"];
                        inventory?: string[];
                        stats?: components["schemas"]["CharacterStats"];
                    };
                };
            };
            /** @description Item not in inventory, wrong slot, or class restriction */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Item or character not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    syncOwner: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "characterId": "chr_abc123",
                 *       "newOwnerAddress": "0xnewowner..."
                 *     }
                 */
                "application/json": {
                    characterId: string;
                    newOwnerAddress: string;
                };
            };
        };
        responses: {
            /** @description Owner synced */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Character"];
                };
            };
            /** @description On-chain ownership mismatch or no heroTokenId */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getParty: {
        parameters: {
            query: {
                characterId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Party with hero and 5 companion slots */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartyResponse"];
                };
            };
            /** @description Character not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    forgeParty: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    heroCharacterId: string;
                    ownerAddress: string;
                    companions: {
                        slotIndex: number;
                        name: string;
                        archetype: string;
                        /** @description JSON string of lore data */
                        backstoryJson: string;
                        raceId?: string;
                        classId?: string;
                        avatarBase64?: string;
                        portraitBase64?: string;
                        /** @default image/png */
                        mimeType?: string;
                    }[];
                };
            };
        };
        responses: {
            /** @description Party forged */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        companions?: components["schemas"]["Companion"][];
                    };
                };
            };
            /** @description Must provide exactly 5 companions */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    linkCompanionTokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "companionIds": [
                 *         "comp_1",
                 *         "comp_2"
                 *       ],
                 *       "tokenIds": [
                 *         100,
                 *         101
                 *       ]
                 *     }
                 */
                "application/json": {
                    companionIds: string[];
                    tokenIds: number[];
                };
            };
        };
        responses: {
            /** @description Tokens linked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success?: boolean;
                    };
                };
            };
        };
    };
    listCompanions: {
        parameters: {
            query: {
                ownerAddress: string;
                /** @description Filter to a specific hero's party */
                heroCharacterId?: string;
                /** @description Set to "true" to list bench companions only */
                unassigned?: "true";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Companion list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        companions?: components["schemas"]["Companion"][];
                    };
                };
            };
        };
    };
    createCompanion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    heroCharacterId: string;
                    ownerAddress: string;
                    slotIndex: number;
                    name: string;
                    archetype: string;
                    backstoryJson: string;
                    avatarBase64?: string;
                    portraitBase64?: string;
                    /** @default image/png */
                    mimeType?: string;
                };
            };
        };
        responses: {
            /** @description Companion created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Companion"];
                };
            };
            /** @description Slot occupied or invalid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    reassignCompanion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    companionId: string;
                    ownerAddress: string;
                    /** @description Null to bench the companion */
                    heroCharacterId?: string | null;
                    slotIndex?: number | null;
                };
            };
        };
        responses: {
            /** @description Companion reassigned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Companion"];
                };
            };
        };
    };
    createBenchCompanion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    ownerAddress: string;
                    name: string;
                    archetype: string;
                    backstoryJson: string;
                    raceId?: string;
                    classId?: string;
                    avatarBase64?: string;
                    portraitBase64?: string;
                    /** @default image/png */
                    mimeType?: string;
                    soulboundTokenId?: number | null;
                };
            };
        };
        responses: {
            /** @description Bench companion created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Companion"];
                };
            };
        };
    };
    generateCompanion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "archetype": "healer",
                 *       "raceId": "high_elf",
                 *       "classId": "cleric"
                 *     }
                 */
                "application/json": {
                    /** @default warrior */
                    archetype?: string;
                    raceId?: string;
                    classId?: string;
                    name?: string;
                };
            };
        };
        responses: {
            /** @description Generated lore and images */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        lore?: {
                            name?: string;
                            epithet?: string;
                            backstory?: string;
                            personality?: string;
                            abilities?: string;
                            appearance?: string;
                        };
                        portraitBase64?: string;
                        avatarBase64?: string;
                        /** @example image/png */
                        mimeType?: string;
                    };
                };
            };
            /** @description AI generation failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getGameState: {
        parameters: {
            query: {
                characterId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full game state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameStateResponse"];
                };
            };
        };
    };
    travel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "characterId": "chr_abc123",
                 *       "targetZoneId": "zone_commons"
                 *     }
                 */
                "application/json": {
                    characterId: string;
                    targetZoneId: string;
                };
            };
        };
        responses: {
            /** @description Traveled successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        character?: components["schemas"]["Character"];
                        zone?: components["schemas"]["Zone"];
                    };
                };
            };
            /** @description Zone not connected or doesn't exist */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    respawn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "characterId": "chr_abc123",
                 *       "atBindPoint": true
                 *     }
                 */
                "application/json": {
                    characterId: string;
                    /**
                     * @description If true, teleport to bind zone
                     * @default true
                     */
                    atBindPoint?: boolean;
                };
            };
        };
        responses: {
            /** @description Character respawned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        character?: components["schemas"]["Character"];
                    };
                };
            };
        };
    };
    gameAction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "characterId": "chr_abc123",
                 *       "message": "I approach the mysterious merchant and ask about rare weapons"
                 *     }
                 */
                "application/json": {
                    characterId: string;
                    /** @description Free-text player action or dialogue */
                    message: string;
                };
            };
        };
        responses: {
            /** @description SSE stream of game master response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Missing characterId or message */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    tokenCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "walletAddress": "0x1234567890abcdef1234567890abcdef12345678",
                 *       "templateId": "tmpl_shadowknight_iksar"
                 *     }
                 */
                "application/json": {
                    walletAddress: string;
                    /** @description Hero template to check requirements for */
                    templateId?: string;
                };
            };
        };
        responses: {
            /** @description Token check result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "allowed": true,
                     *       "requirements": [
                     *         {
                     *           "id": "req_1",
                     *           "label": "GRT Token",
                     *           "tokenAddr": "0xtoken...",
                     *           "minAmount": "100000000000000000000",
                     *           "balance": "500000000000000000000",
                     *           "met": true
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": {
                        allowed?: boolean;
                        requirements?: {
                            id?: string;
                            label?: string;
                            tokenAddr?: string;
                            minAmount?: string;
                            balance?: string;
                            met?: boolean;
                        }[];
                    };
                };
            };
        };
    };
    getCombat: {
        parameters: {
            query: {
                characterId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Combat state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        active?: boolean;
                        state?: components["schemas"]["CombatState"] | null;
                    };
                };
            };
        };
    };
    combatAction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "characterId": "chr_abc123",
                 *       "action": "initiate"
                 *     }
                 */
                "application/json": {
                    characterId: string;
                    /** @enum {string} */
                    action: "initiate" | "tick" | "flee";
                    /** @description Optional mob IDs for "initiate" action */
                    mobTemplateIds?: string[];
                };
            };
        };
        responses: {
            /** @description Combat result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        state?: components["schemas"]["CombatState"];
                    } | {
                        round?: number;
                        state?: components["schemas"]["CombatState"];
                        isOver?: boolean;
                        character?: components["schemas"]["Character"];
                        droppedLoot?: string[];
                    } | {
                        success?: boolean;
                        /** @example fled */
                        outcome?: string;
                    };
                };
            };
            /** @description Character dead, already in combat, or invalid action */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    startBattle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "characterId": "chr_abc123",
                 *       "ownerAddress": "0x1234...",
                 *       "difficulty": "medium"
                 *     }
                 */
                "application/json": {
                    characterId: string;
                    ownerAddress: string;
                    difficulty?: components["schemas"]["BattleDifficulty"];
                };
            };
        };
        responses: {
            /** @description Battle started */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BattleState"];
                };
            };
            /** @description Character not found */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    battleAction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "sessionId": "sess_xyz",
                 *       "action": {
                 *         "actorId": "unit_hero",
                 *         "type": "attack",
                 *         "targetId": "mob_1"
                 *       }
                 *     }
                 */
                "application/json": {
                    sessionId: string;
                    action: components["schemas"]["BattleAction"];
                };
            };
        };
        responses: {
            /** @description Updated battle state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BattleState"];
                };
            };
            /** @description Invalid session or action */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getPvPLobby: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lobby entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "matchId": "pvp_abc",
                     *         "player1Name": "Kazrak",
                     *         "player1Class": "shadowknight",
                     *         "player1Level": 12,
                     *         "partySize": 6,
                     *         "createdAt": "2025-06-01T12:00:00Z"
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["PvPLobbyEntry"][];
                };
            };
        };
    };
    createPvPMatch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "characterId": "chr_abc123",
                 *       "ownerAddress": "0x1234..."
                 *     }
                 */
                "application/json": {
                    characterId: string;
                    ownerAddress: string;
                };
            };
        };
        responses: {
            /** @description Match created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "matchId": "pvp_abc123"
                     *     }
                     */
                    "application/json": {
                        matchId?: string;
                    };
                };
            };
            /** @description Must have full party (5 companions) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    joinPvPMatch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "matchId": "pvp_abc123",
                 *       "characterId": "chr_def456",
                 *       "ownerAddress": "0x5678..."
                 *     }
                 */
                "application/json": {
                    matchId: string;
                    characterId: string;
                    ownerAddress: string;
                };
            };
        };
        responses: {
            /** @description Battle started — returns full battle state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PvPBattleState"];
                };
            };
            /** @description Match not waiting, same player, or party incomplete */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getPvPState: {
        parameters: {
            query: {
                matchId: string;
                /** @description Your character ID (for player-specific view) */
                characterId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Match state (shape depends on status) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example waiting */
                        status?: string;
                        matchId?: string;
                    } | components["schemas"]["PvPBattleState"];
                };
            };
            /** @description Match not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    pvpAction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "matchId": "pvp_abc123",
                 *       "characterId": "chr_abc123",
                 *       "action": {
                 *         "actorId": "unit_hero",
                 *         "type": "attack",
                 *         "targetId": "enemy_unit_1"
                 *       }
                 *     }
                 */
                "application/json": {
                    matchId: string;
                    characterId: string;
                    action: components["schemas"]["BattleAction"];
                };
            };
        };
        responses: {
            /** @description Updated player view */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PvPBattleState"];
                };
            };
            /** @description Not your turn, match not active, or invalid action */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listQuests: {
        parameters: {
            query: {
                characterId: string;
                /** @description Zone to check for available quests */
                zoneId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Quest lists */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        active?: components["schemas"]["CharacterQuest"][];
                        available?: components["schemas"]["Quest"][];
                        /** @description Lookup map of questId → Quest */
                        quests?: {
                            [key: string]: components["schemas"]["Quest"];
                        };
                    };
                };
            };
        };
    };
    questAction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "action": "accept",
                 *       "characterId": "chr_abc123",
                 *       "questId": "quest_rat_slayer"
                 *     }
                 */
                "application/json": {
                    /** @enum {string} */
                    action: "accept" | "progress" | "complete";
                    characterId: string;
                    questId: string;
                    /** @description Required for "progress" action */
                    objectiveId?: string;
                    /**
                     * @description Progress increment amount
                     * @default 1
                     */
                    increment?: number;
                };
            };
        };
        responses: {
            /** @description Quest updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        characterQuest?: components["schemas"]["CharacterQuest"];
                        quest?: components["schemas"]["Quest"];
                    };
                };
            };
            /** @description Prerequisites not met or invalid action */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listItems: {
        parameters: {
            query?: {
                /** @description Single item lookup by ID */
                id?: string;
                /** @description Filter items usable by this class */
                classId?: string;
                /** @description Filter armor by equipment slot */
                slot?: string;
                /** @description Filter by item type */
                type?: "weapon" | "armor";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Item(s) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"] | components["schemas"]["Item"][];
                };
            };
            /** @description Item not found (when using id param) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getMerchants: {
        parameters: {
            query?: {
                /** @description List merchants in this zone */
                zoneId?: string;
                /** @description Get specific merchant */
                merchantId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Merchant(s) with inventory */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Merchant"] | components["schemas"]["Merchant"][];
                };
            };
            /** @description Missing zoneId or merchantId */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    merchantTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "characterId": "chr_abc123",
                 *       "merchantId": "npc_merchant_qeynos",
                 *       "action": "buy",
                 *       "itemId": "rusty_short_sword",
                 *       "quantity": 1
                 *     }
                 */
                "application/json": {
                    characterId: string;
                    merchantId: string;
                    /** @enum {string} */
                    action: "buy" | "sell";
                    itemId: string;
                    /** @default 1 */
                    quantity?: number;
                };
            };
        };
        responses: {
            /** @description Transaction result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        /** @description Present on buy */
                        bought?: number;
                        /** @description Present on sell */
                        sold?: number;
                        itemId?: string;
                        /** @description In copper (buy only) */
                        totalCost?: number;
                        /** @description In copper (sell only) */
                        saleValue?: number;
                        currency?: components["schemas"]["Currency"];
                    };
                };
            };
            /** @description Insufficient funds, item not available, or not in inventory */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getLeaderboard: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Filter by class */
                classId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ranked leaderboard */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "rank": 1,
                     *         "id": "chr_abc123",
                     *         "name": "Kazrak",
                     *         "raceId": "iksar",
                     *         "classId": "shadowknight",
                     *         "level": 25,
                     *         "xp": 12500,
                     *         "currentZoneId": "zone_sebilis",
                     *         "ownerAddress": "0x1234...",
                     *         "portraitIpfs": "QmXyz...",
                     *         "templateId": "tmpl_shadowknight_iksar"
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["LeaderboardEntry"][];
                };
            };
        };
    };
    requestFaucet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "address": "0x1234567890abcdef1234567890abcdef12345678"
                 *     }
                 */
                "application/json": {
                    address: string;
                };
            };
        };
        responses: {
            /** @description ETH sent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "ok": true,
                     *       "hash": "0xabc123..."
                     *     }
                     */
                    "application/json": {
                        ok?: boolean;
                        /** @description Transaction hash */
                        hash?: string;
                    };
                };
            };
            /** @description Invalid address or not on Hardhat network */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
